### ISSUE TITLE
It is difficult to isolate Artefactual code from vendor libraries

### ISSUE THREAD

**Issue by ross-spencer** [artefactual-labs/AIPscan#102]
07d46ded introduced a vendor library for Font Awesome. This helpfully allows us to tease apart our code files vs. those of fontawesome. We still have other vendor libraries and so if we want to do something specific with our own, e.g. linting, then the exceptions needed in automation  scripts get more complicated. 

Consider moving everything to their own vendor library now as well as introduce vendor folders for new code while we have a good opportunity in the early phases of this project.

**Comment by ross-spencer** [comment]
Possibly related? https://github.com/artefactual-labs/AIPscan/issues/82

**Comment by mcantelon** [comment]
Merged PR to bundle assets using Vite build.
