### ISSUE TITLE
Test: valid Storage Service URL, username, and API key are used

### ISSUE THREAD

**Issue by peterVG** [artefactual-labs/AIPscan#112]
Related to Issue https://github.com/artefactual-labs/AIPscan/issues/111

Problem: can't expose a live SS URL & API Key in this project's Git repo. 
-- Should we use ENV variables? Is that too awkward to support across deployments?
-- Could we prepare stubs/fixtures for this test instead? Doesn't it need to make a live `requests` call to be a valid test?

**Comment by tw4l** [comment]
Resolved in https://github.com/artefactual-labs/AIPscan/commit/c4eb77756d43897d9c1b9cf58acd19c6898dd9b2
