### ISSUE TITLE
Problem: date range pick values aren't sticky

### ISSUE THREAD

**Issue by peterVG** [artefactual-labs/AIPscan#124]
Current behaviour: User selects a start and end date for a report. The report is generated in another browser tab. The user returns to the Reports tab where the start and end date are reset to January 1st of the current year and today.

Expected behaviour: The time range set when the report is triggered is still there when the user returns to the Reports tab.

**Comment by ablwr** [comment]
Closed via https://github.com/artefactual-labs/AIPscan/pull/127
