### ISSUE TITLE
Show active tab in main menu

### ISSUE THREAD

**Issue by peterVG** [artefactual-labs/AIPscan#13]

**Comment by ross-spencer** [comment]
I presume you're just looking for an indicator like the text being highlighted when one is on a specific tab, like here in the storage service listings? 

![image](https://user-images.githubusercontent.com/1880412/86834438-d4f24380-c068-11ea-8d41-7ddb45520df3.png)

**Comment by peterVG** [comment]
Yes, exactly. Some Bootstrap/jQuery tweaking needed here.

**Comment by mcantelon** [comment]
Added PR for this: https://github.com/artefactual-labs/AIPscan/pull/220

**Comment by mcantelon** [comment]
PR merged!
