### ISSUE TITLE
Problem: AIPs aren't associated to their origin pipeline/dashboard in AIPscan

### ISSUE THREAD

**Issue by tw4l** [artefactual-labs/AIPscan#136]
It's not currently possible for a user of AIPscan to determine which Archivematica dashboard they should go to to download a particular AIP they see in AIPscan. It would be helpful to add this information and provide a link to the appropriate dashboard if possible.

**Comment by peterVG** [comment]
The feature works well. The dashboard IP shows as a hyperlink in the profile section for each AIP. 

<img width="710" alt="Screen Shot 2021-06-09 at 12 50 20 PM" src="https://user-images.githubusercontent.com/672121/121420242-af795400-c921-11eb-9f31-8ba5c0e143c2.png">


Despite using a domain name based address for the SS API location, the pipeline URI shows as a bare-bones IP which is better IMHO, assuming its correct of course, which it was in my case:

<img width="862" alt="Screen Shot 2021-06-09 at 12 50 48 PM" src="https://user-images.githubusercontent.com/672121/121420275-b902bc00-c921-11eb-86b2-c240c992fe9c.png">

**Comment by tw4l** [comment]
Thanks Peter - the value in AIPscan will be whatever the `remote_name` value for the Pipeline is in the Storage Service. So in your case it looks like that's an IP address, but it could also be a fully qualified domain name depending on the Storage Service config.
