### ISSUE TITLE
report an accurate last-modified-date from creating application

### ISSUE THREAD

**Issue by peterVG** [artefactual-labs/AIPscan#14]

**Comment by ross-spencer** [comment]
If we can split this out into an issue for modified date first, and a creation date second that would be good. I learned this from the Java API back in the day. Creation date was ultimately never particularly reliable. Not all file-systems generated it. See [this list of metadata properties](https://en.wikipedia.org/wiki/Comparison_of_file_systems#Metadata) in Wikipedia. It's already way better than years back, but for a while, we'd be transferring windows files to an enterprise system on Linux/ext3 for example, and simply losing them. 

So yeah, if we can focus on modified date first, then I think that's in-line with a reasonable digital preservation standard. 

And then we can look at tools you've mentioned previously like Tika which have the ability to extract that information from parsing the digital objects that are self-describing and maintain this info. 

Regarding METS - I can see the problem with `premis:dateCreatedByApplication` - I think this is a bug. Our initial rsync should be preserving that. I will have a look.

**Comment by ross-spencer** [comment]
O wait: `premis:dateCreatedByApplication` that's a problem with `metsrw` right? You haven't an easy way to access that value from its API? -- If that's the case, can you log an issue against the library in archivematica/issues? 

Otherwise, if I'm still lost in the wind here - the ticket might need more extrapolation! :stuck_out_tongue:

**Comment by peterVG** [comment]
I can get a `premis:dateCreatedByApplication` value from `metsrw` but it's not accurate. It's basically Archivematica's last modified date.

**Comment by ross-spencer** [comment]
@peterVG I think maybe it is a local thing, perhaps how the sample data was downloaded? 

I have a sample script that I use for old-date testing: [here](https://gist.github.com/ross-spencer/cc078c662fdeb161749b3bd02fc31302).

I create random files and then modify all of the modified dates to something older, and I can see the following if I then transfer those created files:
```
$ cat DATES-METS.3c06dc1a-9331-4683-82e1-eb21facb9aa9.xml | grep dateCreatedByApplication
    <premis:dateCreatedByApplication>1991-08-03</premis:dateCreatedByApplication>
    <premis:dateCreatedByApplication>2016-03-04</premis:dateCreatedByApplication>
    <premis:dateCreatedByApplication>1982-11-04</premis:dateCreatedByApplication>
    <premis:dateCreatedByApplication>2009-04-20</premis:dateCreatedByApplication>
    <premis:dateCreatedByApplication>2011-08-09</premis:dateCreatedByApplication>
    <premis:dateCreatedByApplication>1974-02-10</premis:dateCreatedByApplication>
    <premis:dateCreatedByApplication>2004-03-08</premis:dateCreatedByApplication>
    <premis:dateCreatedByApplication>1971-10-24</premis:dateCreatedByApplication>
    <premis:dateCreatedByApplication>2015-11-13</premis:dateCreatedByApplication>
    <premis:dateCreatedByApplication>1984-10-25</premis:dateCreatedByApplication>
    <premis:dateCreatedByApplication>1976-10-20</premis:dateCreatedByApplication>
    <premis:dateCreatedByApplication>2009-08-09</premis:dateCreatedByApplication>
    <premis:dateCreatedByApplication>2020-07-10</premis:dateCreatedByApplication>
```

I've put a copy in your sample-data folder `/home/artefactual/old-dates`, and added 50 example files:
```
-rw-rw-r-- 1 artefactual artefactual   11 May 27  1994 file_43.md
-rw-rw-r-- 1 artefactual artefactual   11 Jul 12  1987 file_44.md
-rw-rw-r-- 1 artefactual artefactual   11 Feb 22  1999 file_45.md
-rw-rw-r-- 1 artefactual artefactual   11 May 12  1987 file_46.md
-rw-rw-r-- 1 artefactual artefactual   11 May  2  1995 file_47.md
-rw-rw-r-- 1 artefactual artefactual   11 Apr 26  2013 file_48.md
-rw-rw-r-- 1 artefactual artefactual   11 Aug 13  2002 file_49.md
-rw-rw-r-- 1 artefactual artefactual   11 Oct 16  1972 file_5.md
-rw-rw-r-- 1 artefactual artefactual   11 Jun 22  2014 file_6.md
-rw-rw-r-- 1 artefactual artefactual   11 Nov 12  1972 file_7.md
-rw-rw-r-- 1 artefactual artefactual   11 Feb 11  1978 file_8.md
-rw-rw-r-- 1 artefactual artefactual   11 Jul 26  1996 file_9.md
```
I wanted to try a transfer out tonight, but I couldn't access your storage service, and Archivematica thinks that the API key has changed so it can't list the files in the transfer browser. A quick fix for you, but I didn't want to go and change anything in case you have everything configured for something else. 

If you give that old-dates transfer a whirl you might have more luck. Let me know if not.

**Comment by ross-spencer** [comment]
Notes on this added to the upstream issue: https://github.com/archivematica/Issues/issues/703#issuecomment-687287478

Fixed by commit:  https://github.com/artefactual-labs/AIPscan/commit/f0b753edca1e839bb2493da6045f518f4b43c5cd
