### ISSUE TITLE
Problem:  display of total new downloaded AIPs is a bit ambiguous

### ISSUE THREAD

**Issue by peterVG** [artefactual-labs/AIPscan#143]
Today was the first time I used this non-duplication feature https://github.com/artefactual-labs/AIPscan/issues/6 which works great. 

However, I'm a little concerned about how AIPscan reports out from this functionality. IMHO its not as clear as it could be.

Firstly, a nit-pick. If AIPscan Aggregator encounters a METS file it has already parsed, then the Fetch Job monitor output should read: "SKIPPED already parsed 1. METS.86027...." instead of "SUCCESS parsing 1. METS.86027..."

<img width="562" alt="Screen Shot 2021-06-07 at 12 09 01 PM" src="https://user-images.githubusercontent.com/672121/121074964-6db5a580-c789-11eb-978d-fd6698d13a5c.png">

More importantly: reporting how many new AIPs were scanned (or old ones skipped) is not so clear ATM:

<img width="1442" alt="Screen Shot 2021-06-07 at 12 11 58 PM" src="https://user-images.githubusercontent.com/672121/121076083-d6515200-c78a-11eb-8691-e61b3cd3b9ea.png">

In the initial version of AIPscan, I was just trying to make clear that there may be X number of packages in a SS but you are only seeing data about a subset, Y number of AIPs. There was one column for # of packages and one for # of downloaded AIPs (e.g. number of AIPs with data in this AIPscan instance) 

That has gotten a little more convoluted now that we have more data to report. My second Fetch Job in the screencapture above did not encounter any new AIPs. Yet the "AIP METS downloaded" column reports "42". From.a developer's perspective we realize that this is correct because AIPscan still has to download a METS file to see if it's parsed it already. But from a user perspective its confusing. Why did you download 42 AIP METS but report 0 "current AIPs". And what is a "current AIP". It's being used in the context of AIPscan's internal state but from an end-user point-of-view this is a confusing term. What makes an AIP "current" here?

My suggestion is to trim it back down to two columns. We are actually providing all the statistical info about packages in the repository under the "i" icon in the "Packages in SS" column. A side benefit of this enhancement is that it will now also show historical differences. E.g. I now have 100 more packages than last time I ran a Fetch Job on DD-MM-YYYY."

So maybe we could just rename the second column: "new AIPS scanned" or "AIPs added"

This language would also indicate that there may be a difference between AIPs that may be present in an Archivematica system and the ones that have actually been "scanned" into AIPscan as part of that particular fetch job.

**Comment by tw4l** [comment]
> Firstly, a nit-pick. If AIPscan Aggregator encounters a METS file it has already parsed, then the Fetch Job monitor output should read: "SKIPPED already parsed 1. METS.86027...." instead of "SUCCESS parsing 1. METS.86027..."

I agree ideally that would be the case, but it's being based on the Celery task status so would prove complicated. Given the other higher priority work at the moment, maybe we could leave with this for now?

**Comment by peterVG** [comment]
Yes, the first nit-pick is totally not a priority ATM. I thought it was a simple IF statement we could add to output alternate text but I forgot all about the Celery integration here and its terminology dependence, sorry.

**Comment by peterVG** [comment]
Fixed in https://github.com/artefactual-labs/AIPscan/pull/144
