### ISSUE TITLE
Round up file size from bytes to MB & GB where appropriate

### ISSUE THREAD

**Issue by peterVG** [artefactual-labs/AIPscan#15]

**Comment by ross-spencer** [comment]
A nice option we have, and is something we're slowly adopting in Archivematica is to use a helper. So JNinja offers:

And in the AIP view page that will look like:
```diff
git diff AIPscan/Reporter/templates/view_aip.html
diff --git a/AIPscan/Reporter/templates/view_aip.html b/AIPscan/Reporter/templates/view_aip.html
index 31e5967..ee9b03e 100644
--- a/AIPscan/Reporter/templates/view_aip.html
+++ b/AIPscan/Reporter/templates/view_aip.html
@@ -27,7 +27,7 @@
       <tr>
         <td>{{ original.name }}</td>
         <td>{{ original.uuid }}</td>
-        <td>{{ original.size }}</td>
+        <td>{{ original.size|filesizeformat(true) }}</td>
         <td>{{ original.puid }}</td>
         <td>{{ original.format }} {% if original.format_version != None %} {{original.format_version}}{% endif %}</td>
         <td><a href="{{ url_for('reporter.view_original', id=original.id ) }}"><button type="button" class="btn btn-info" style="margin-bottom: 5px;">Events</button></a>
```

![image](https://user-images.githubusercontent.com/1880412/86828496-4f1eca00-c061-11ea-9a2d-0f972cac13ef.png)

So, if we can make our headers more generic in title, and add this helper in, we'll get formatting for free.

**Comment by peterVG** [comment]
Yeah, I had added this Helper a few commits back to use in the Reports: https://github.com/artefactual-labs/AIPscan/blob/main/AIPscan/helpers.py

One issue I had was that the Datatables Size sorting didn't work if I mixed in "Bytes", "KiB", "GiB" because then it did string sorting instead of integer sorting. So I ended using both a "Size in bytes" column (for sorting) and a "Size" column (e.g. KiB, MiB, GiB) for human-readable display. Will using Jinja's `filesizeformat` allow us to maintain Datatables sorting?

**Comment by ross-spencer** [comment]
> Will using Jinja's filesizeformat allow us to maintain Datatables sorting?

Good question, I'll have a look, and I understand completely. I wonder if Dtatables can be configured to sort on a table attribute vs. what's displayed instead? That seems like good HTML data practice.
