### ISSUE TITLE
Problem: The AIP Contents print format still includes DataTables widgets

### ISSUE THREAD

**Issue by peterVG** [artefactual-labs/AIPscan#150]
The DataTables search and paging widgets appear above and below the rows in the report on each page.

Not all the columns are displayed on the report (probably can't be, even when switching to Landscape mode?)

<img width="1225" alt="Screen Shot 2021-06-09 at 9 10 04 AM" src="https://user-images.githubusercontent.com/672121/121391259-058acf00-c903-11eb-8112-4099557d870b.png">

Maybe this report only works as a CSV dump? Should we just take away the Print button rather than tackle these other issues?

**Comment by tw4l** [comment]
Fixed in #154
