### ISSUE TITLE
PROBLEM: There is no organizing logic for the order of reports on the selection page

### ISSUE THREAD

**Issue by peterVG** [artefactual-labs/AIPscan#151]
Why is AIP contents first? Alphabetical? Happenstance?

<img width="1806" alt="Screen Shot 2021-06-09 at 9 16 24 AM" src="https://user-images.githubusercontent.com/672121/121391572-5ef2fe00-c903-11eb-845a-ad99849bdbdd.png">

I propose that we try to group the reports by similar function and order based on what we expect to be of highest use or interest.

My first stab:

1) AIP storage locations
2) AIP contents
3) Largest files
4) File format count
5) Format version count
6) File format
7) File format version
8) File format (preservation)
9) Preservation derivatives
10) User ingest log

**Comment by peterVG** [comment]
Update. I propose we drop the **2. AIP contents** report from the list altogether. At least for the upcoming 0.5.0 tag. See https://github.com/artefactual-labs/AIPscan/issues/152#issue-916503386

**Comment by tw4l** [comment]
@peterVG I'll leave discussion on the AIP contents report for the associated issue but I like your proposed reordering. Go ahead and make the change if you have time and I'll be happy to review.

**Comment by tw4l** [comment]
Keep in mind that there's also a File format version (preservation) report to slot in between 8 and 9 above. It just doesn't show unless there are PUIDs for preservation files in a Storage Service (usually because of manual normalization).

**Comment by peterVG** [comment]
Pull request:

<img width="1208" alt="Screen Shot 2021-06-10 at 8 24 59 AM" src="https://user-images.githubusercontent.com/672121/121552475-5c58dd00-c9c5-11eb-8780-d87bc53b7f3b.png">

**Comment by peterVG** [comment]
Even prettier IMHO after another re-org (and fixes from 1st review). 

See https://github.com/artefactual-labs/AIPscan/pull/156

<img width="1327" alt="Screen Shot 2021-06-10 at 10 10 59 AM" src="https://user-images.githubusercontent.com/672121/121568541-a8f7e480-c9d4-11eb-9003-905fd88c9927.png">
