### ISSUE TITLE
Problem: Date range filtering is not implemented for AIP contents report

### ISSUE THREAD

**Issue by peterVG** [artefactual-labs/AIPscan#152]
Currently the report is generated for all AIPs in the database, regardless of any date range filters that might have been set by the user. EDIT: this looks to have been intentional but leaves the user wondering why date range works on similar reports but not this one. The AIP ingest date is the third column you see in the report. SInce its such a large report it would be useful to narrow down contents by these dates.

There is another usability issue related to this report as it has a very long horizontal scroll which is hard to read. 

This report also has an open print formatting bug: https://github.com/artefactual-labs/AIPscan/issues/150  

All things considered, I am actually not convinced that this report offers something better over the AIP contents browsing that is currently provided via the AIPscan GUI. The only thing it can't do right now is date range filtering (which is broken or not implemented for the report anyway).

Therefore, I would like to propose that we "hide" this report from the upcoming 0.5.0 release GUI rather than spend more time on it ATM.

**Comment by tw4l** [comment]
The AIP Contents report was reworked in https://github.com/artefactual-labs/AIPscan/pull/154 and now has filtering by start and end date.
