### ISSUE TITLE
Provide download link for original and preservation copy files

### ISSUE THREAD

**Issue by peterVG** [artefactual-labs/AIPscan#16]
Does this cross the line from an Aggregator/Reporting component to an Access/Retrieval component?

**Comment by tw4l** [comment]
Client feedback has indicated this may be seen as a security risk. PR https://github.com/artefactual-labs/AIPscan/pull/148 adds a link to the Dashboard URL for each AIP to facilitate downloading the AIP from the Dashboard's Archival Storage tab.

**Comment by mcantelon** [comment]
Closing as the security concern/scope concerns make sense.
