### ISSUE TITLE
Feature: Schedule Fetch Job

### ISSUE THREAD

**Issue by rayzilt** [artefactual-labs/AIPscan#181]
We like to see the possibility to schedule a new fetch job.

The possibility to schedule a task in AIPScan is preferred, or by using an API call to allow scheduling by cron for example.

**Comment by mcantelon** [comment]
A CLI tool to fetch AIPs (based on the rough work we did earlier) has been merged so automatic, scheduled updating of AIPscan is now possible from the main branch.
