### ISSUE TITLE
AIPScan database not updated if AIP deleted from storage service

### ISSUE THREAD

**Issue by aseles13** [artefactual-labs/AIPscan#199]
**Current behaviour:** If AIPs are deleted from the storage service the AIPScan database will not change, meaning that deleted AIP is still appearing in search results. 
**Expected behaviour:** As AIPScan is a mechanism for searching and reporting against AIPs in the storage service if there changes that need to be made, they should be reflected in database results.
Related issues:
[Issue 91: Delete storage service doesn’t remove agents](https://github.com/artefactual-labs/AIPscan/issues/91)
[Issue 40: Delete fetch job times out](https://github.com/artefactual-labs/AIPscan/issues/40)

**Comment by mcantelon** [comment]
Mel's fix for this has been merged!
