### ISSUE TITLE
Ability to schedule chron jobs rather than manually triggering AIPScan updates

### ISSUE THREAD

**Issue by aseles13** [artefactual-labs/AIPscan#203]
**Current behaviour:** To update the AIPScan users must run a script manually to update the AIPScan database

**Expected behaviour:** AIPScan should have the ability to support chron jobs to allow users to schedule when to run AIPScan database updates. 

Related issues: 
[Issue 181: Feature: Schedule Fetch Job](https://github.com/artefactual-labs/AIPscan/issues/181)
[Issue 1: AIPScan cannot report on AIPs added post fetch-job](https://github.com/artefactual-labs/AIPscan/issues/1)

**Comment by mcantelon** [comment]
We can address this by adding the ability to run fetch requests using a command-line tool (that can be ran on a scheduled basis via crontab). I roughed this functionality out awhile back in a dev branch, but there's some work I've done in another "work in progress" pull request (to generate random test data to help during development) that, when merged, will make is easier to complete this functionality. I'll update this issue when that work's completed and merged.

**Comment by mcantelon** [comment]
A PR's ready for review that adds a script to automatically update AIPs:

https://github.com/artefactual-labs/AIPscan/pull/237

**Comment by mcantelon** [comment]
A script to fetch AIPs has been merged.
