### ISSUE TITLE
PROBLEM: AIPs page loads slowly

### ISSUE THREAD

**Issue by sarah-mason** [artefactual-labs/AIPscan#209]
The AIPs view page can take several minutes to load in an instance, particularly those with a lot of AIPs in the database. No further searching or browsing of AIPs can take place at this time. If you click back to the AIPs page after viewing an AIP, it will take several minutes to load again.

A potential suggested fix was to add the search box to the main page where Fetch jobs are initiated to prevent the need to load the entire AIP view. There may also be other database optimisation options.

**Comment by mcantelon** [comment]
Thanks Sarah... we'll take a look at potential solutions!

**Comment by mcantelon** [comment]
I think I might know the underlying issue and am going to start on a fix.

**Comment by mcantelon** [comment]
A pull request has been created to fix this: https://github.com/artefactual-labs/AIPscan/pull/215

I'll update this issue when it's reviewed and merged.

**Comment by mcantelon** [comment]
I've merged a fix for this.
