### ISSUE TITLE
Pylint: Bare-excepts in-line

### ISSUE THREAD

**Issue by ross-spencer** [artefactual-labs/AIPscan#29]
From `pylint`:
```
[W0702 bare-except] No exception type(s) specified File: Aggregator/tasks.py, line 326, in get_mets
[W0702 bare-except] No exception type(s) specified File: Aggregator/views.py, line 187, in new_fetch_job
```
These are pretty key to fix-up early. If you take Archivematica, one of the things that is lost in some of our `except Exception` blocks is the context. Dealing with primitives it might be quite obvious initially that the exception seen by the developer initially was an `IndexError`, `ValueError` etc. But as we start dealing with libraries, then we lost that ability to quickly walk back and correct this and say, okay, we're seeing a `DjangoThingyException` here, so let's work with that.

The primary reason for not having a bare except is that it masks other exceptions because it will catch all exception objects and there might be places further down the stack we're not expecting something. We should let the application fail/respond with an error at these points so that they can be managed correctly.

**Comment by peterVG** [comment]
Yes, good practice, thank you. I'm surprised `pylint` didn't find any more actuall ;-) I'll clean these up when I return to the code.

**Comment by ross-spencer** [comment]
We've captured both of these now as we search today with: `pylint $(find * | grep py$) | grep "bare-except"`
