### ISSUE TITLE
Pylint: unused variables

### ISSUE THREAD

**Issue by ross-spencer** [artefactual-labs/AIPscan#30]
From `pylint`:
```
[W0612 unused-variable] Unused variable 'dateTimeObjStart' File: Aggregator/tasks.py, line 171, in package_lists_request
[W0612 unused-variable] Unused variable 'storageServices' File: Aggregator/views.py, line 118, in delete_storage_service
[W0612 unused-variable] Unused variable 'delta' File: Reporter/views.py, line 135, in report_formats_count
[W0612 unused-variable] Unused variable 'key' File: Reporter/views.py, line 292, in plot_formats_count
```
Catching these are always great as you either, a) want to use them and for some reason you're not! or b) obviously you're not using them and this memory isn't important to keep around and manipulate. 

A cool little thing I learned in Golang and then realized worked in Python is the `_` syntax. This is useful for loops where you're not using all of the attributes:

```
for key, value in some_dictionary:
   print(value)
```
Should become:
```
for _, value in some_dictionary:
   print(value)
```
Where `key` isn't used. 

Underscore can be used before the assignment operator on all functions returning something. They can be helpful for indicating that there is a potential result to handle, but that you're not working with it yet.

**Comment by peterVG** [comment]
Thanks, will clean these up when I return to the code and replace that `key` with `_` if it is in fact not needed.

**Comment by ross-spencer** [comment]
This is looking better, no "Unused variables" as we search today using: `$ pylint $(find * | grep py$) | grep "Unused variable`.
