### ISSUE TITLE
Let's use isort

### ISSUE THREAD

**Issue by ross-spencer** [artefactual-labs/AIPscan#31]
We have a proposed ADR: https://adr.archivematica.org/0004-isort-import-ordering.html in general I do think it makes life easier, and it's one less thing to make CR subjective. And one less thing to introduce inconsistency across modules. 

I ran `pylint` before and after, and the score was nice to read:

* Cmd: `artefactual-labs/AIPscan/AIPscan$ isort $(find * | grep .py$)`
* Pylint output: `Your code has been rated at 7.32/10 (previous run: 6.99/10, +0.33)`

**Comment by peterVG** [comment]
Okay, sounds good. Should we run it as one repo-wide batch and merge? Too bad we don't have tests to run afterwards. I'm a little concerned about circular imports (e.g. an import being called too early/late). I ran into these when re-factoring to blueprints. But that was basically confined to this file: https://github.com/artefactual-labs/AIPscan/blob/main/AIPscan/__init__.py So I know where to look if things break after the isort.

**Comment by ross-spencer** [comment]
>  Should we run it as one repo-wide batch and merge? 

Perfect!

**Minus `__init__.py`**

Hehe! I can can confirm that circular imports in that file will cause a problem, but also, I think that just means initially, we can leave that particular `__init__.py` out of the `isort` mix. 

I feel it would be good to get the circular imports resolved in time too. I tend to look at these as clues for improving architecture. I did have a look last night before I saw your update. I'm not familiar enough with the code yet to know the objects and the way they're being passed around to have a solution for this. I started looking at [this blog](https://flask.palletsprojects.com/en/1.1.x/patterns/appfactories/) which gives an SQLAlchemy example but I didn't quite complete that trail of thought before moving onto another piece. It looks like maybe the celery context manager is the only other one impacted. I'll read up a little more on the Blueprint and factory pattern.

![warhold-factory](https://media3.giphy.com/media/fxOk71qCsFIqLpBTSu/giphy.gif?cid=ecf05e4779908f552070dfe8f063a3b019051418d0029eab&rid=giphy.gif)

**Comment by ross-spencer** [comment]
With linting errors now resolved I had a brief look into this. It seems like the main concern is making isort compatible with Black, however, with [these options](https://black.readthedocs.io/en/stable/compatible_configs.html#isort) the isort defaults may be good enough (should be, i.e. it is less effort to maintain and already de-facto standardised). 

The output of a draft PR for this is [here](https://github.com/artefactual-labs/AIPscan/pull/105/files) and it all looks fairly sensible. cc. @tw4l @peterVG

**Comment by tw4l** [comment]
@ross-spencer I just left a review for the PR and appreciate the extra detail from your last comment here! The PR looks ready to merge to me. Nice work!

**Comment by ross-spencer** [comment]
Closed via https://github.com/artefactual-labs/AIPscan/pull/105
