### ISSUE TITLE
Shall we enable branch protection now?

### ISSUE THREAD

**Issue by ross-spencer** [artefactual-labs/AIPscan#32]
Branch protection is one of the tools we use to help improve the AtoM/Archivematica/Docs workflows. The basic rule is that the `main` branch is protected and it requires one CR to merge. Like those projects, each PR would be connected to an issue. I do think it is better in the long-term to do this as early as possible. It guarantees always having two developers involved in any particular change so increases the chances of others being involved. But I understand it's desirable in the short term to be able to merge fast. But what do you think @peterVG?

**Comment by peterVG** [comment]
@ross-spencer I think AIPscan has passed its initial sprint of development to get it up and running. It was nice to be able to merge fast but the app is now well-defined enough and needs to get stabilized, so +1 to this. Will practice branch protection from this point forward.
