### ISSUE TITLE
There are few docstrings

### ISSUE THREAD

**Issue by ross-spencer** [artefactual-labs/AIPscan#33]
We have a documented standard for `docstrings` in Archivematica: [here](https://wiki.archivematica.org/Contribute_code#Code_Style_Guide_For_Archivematica).

It would be good to get some basic ones in as we start to move through the code-review work. 

My preference is to at least get a single-line `dosctring` specified for most functions: 
```
def function(a, b):
    """Do X and return a list."""
```
And if necessary basic multi-line strings:
```
def function(a, b):
    """Do X and return a list.

   I needed to use more space to describe the function here. As I couldn't fit 
   it into a single line
   """
```
In time, we can add parameters but I think as this code will be rapidly changing, just getting into the habit of the basics will be enough. Parameters will be changing name/type/returns for a wee-bit. 

**NB.** I'll join this work as I go through the code as well. I can't imagine it will be a single commit `here are all the docstrings` but maybe it can be? 

**Style**

I erroneously noted `docstrings` can be 79 characters to Tessa, but it looks like in the [style guide](https://www.python.org/dev/peps/pep-0008/) they are:

> Some teams strongly prefer a longer line length. For code maintained exclusively or primarily by a team that can reach agreement on this issue, it is okay to increase the line length limit up to 99 characters, provided that comments and docstrings are still wrapped at 72 characters.

> The Python standard library is conservative and requires limiting lines to 79 characters (and docstrings/comments to 72). 

So TIL. 

**Additional**

**NB.** We should try and get an encoding at the top of our scripts too: `# -*- coding: utf-8 -*-` we do this fairly inconsistently in the AM code-base but it's not something we don't do. While it's technically mostly only needed for code using non-ASCII code-points, e.g. you might see it in tests using Unicode parameters, it's also just a good forward-looking thing to do.that isn't so anglo-focused. And also, gives the script a pleasing to look at header.

**Comment by tw4l** [comment]
This is being incrementally improved through refactoring
