### ISSUE TITLE
report an accurate created-date from creating application

### ISSUE THREAD

**Issue by peterVG** [artefactual-labs/AIPscan#34]
see related issue https://github.com/artefactual-labs/AIPscan/issues/14

**Comment by ross-spencer** [comment]
I left some notes on this here: https://github.com/archivematica/Issues/issues/703#issuecomment-687287478

And have added the field into the database and summary reports here: https://github.com/artefactual-labs/AIPscan/pull/51/commits/f0b753edca1e839bb2493da6045f518f4b43c5cd
