### ISSUE TITLE
AIPscan fails to fetch AIPs with large sizes

### ISSUE THREAD

**Issue by hakamine** [artefactual-labs/AIPscan#346]
AIPscan failed to fetch a 9GB AIP on a client instance. The following error was shown in the celery logs:

```
...
celery[3041]:   File "/usr/share/archivematica/virtualenvs/AIPscan/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read>
celery[3041]: 	packet.raise_for_error()
celery[3041]:   File "/usr/share/archivematica/virtualenvs/AIPscan/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_fo>
celery[3041]: 	err.raise_mysql_exception(self._data)
celery[3041]:   File "/usr/share/archivematica/virtualenvs/AIPscan/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_e>
celery[3041]: 	raise errorclass(errno, errval)
celery[3041]: sqlalchemy.exc.DataError: (pymysql.err.DataError) (1264, "Out of range value for column 'size' at row 1")
celery[3041]: [SQL: INSERT INTO aip (uuid, transfer_name, create_date, mets_sha256, size, storage_service_id, storage_location_id, fetch_jo>
celery[3041]: [parameters: {'uuid': '2fc6b405-a472-4695-84b4-41ae1a2f597b', 'transfer_name': 'X86065_008_AVP', 'create_date': datetime.date>
Oct 17 16:47:30 ts-am-prd-new celery[3041]: (Background on this error at: http://sqlalche.me/e/9h9h)
```

In AIPscan the field type for the AIP size if defined here: https://github.com/artefactual-labs/AIPscan/blob/main/AIPscan/models.py#L328

which is an Integer (can hold max value of 2GB if signed, 4GB if unsigned). 

In order to be able to accept bigger AIP sizes, it looks like the schema would need to be migrated to use a BigInteger field (https://docs.sqlalchemy.org/en/13/core/type_basics.html#sqlalchemy.types.BigInteger )

(as for comparison, although not using SQLAlchemy, the Storage Service is using a BigInteger field for package sizes, as per https://github.com/artefactual/archivematica-storage-service/blob/qa/0.x/storage_service/locations/models/package.py#L81 )

**Comment by mcantelon** [comment]
PR, for CR, to fix: https://github.com/artefactual-labs/AIPscan/pull/348

**Comment by mcantelon** [comment]
I've merged the fix. Let me know if you run into any iassues with it!
