### ISSUE TITLE
Provide a breakdown of all packages in SS, not just the AIPs included in reports

### ISSUE THREAD

**Issue by peterVG** [artefactual-labs/AIPscan#47]
Include a log of the Exception errors that were reported for each.

Provide this count on the reports themselves?

**Comment by joel-simpson** [comment]
This could also be framed as a report on what AIPScan includes in its database and what it doesn't. That's not just about errors (i.e. couldn't scan x AIPs) but also about helping users reconcile what is in AIPScan with what is in their storage system, including all packages, including DIPs, replicated AIPs, transfers, SIPs etc. 
One idea we discussed was providing an explicit way for users to reconcile what they see in the Storage Service (whether through SS UI or the Archival Storage tab) with what is included in AIPScan. This should give users confidence in the accuracy of data stored in AIPScan.

**Comment by ross-spencer** [comment]
I have got as far as cleaning up some of the METS work to make it easier to see where we need to log these issues. What I haven't  figured out yet, is where to record them:

1. An errors table with a foreign key to the AIP and files (original/preservation) causing a problem?
2. Errors in the AIP or 'files' tables?

And we need to add a summary to the storage service view as well. 

I believe there are currently two places to log errors in processing:

1. Overall error processing the METS: [here](https://github.com/artefactual-labs/AIPscan/blob/852e3d25ab3a78e27870e5b1c798a5f91953ffb8/AIPscan/Aggregator/tasks.py#L286-L290)
2. Problem processing a file: [here](https://github.com/artefactual-labs/AIPscan/blob/852e3d25ab3a78e27870e5b1c798a5f91953ffb8/AIPscan/Aggregator/database_helpers.py#L184-L188). The problem with this particular except right now is that the error assumes ISO file formats but it could really be any format, and so it might be better to log the entire file as something like "not able to process" and then move on.

**Comment by peterVG** [comment]
To spit up Joel's recommendation to have a way to report out which SS packages have been left out of AIPscan (e.g. DIPs, deleted packages, replicated packages, transfers in backlog) from any error handling functionality, I've created a new issue for the former. The way it's worded (and the recommended implementation) is inspired by the thinking around Issue https://github.com/artefactual-labs/AIPscan/issues/95.

See Issue https://github.com/artefactual-labs/AIPscan/issues/110

**Comment by peterVG** [comment]
GUI option 1: display stats in small, greyed out text below total package count.

<img width="1145" alt="Screen Shot 2021-02-21 at 10 06 38 AM" src="https://user-images.githubusercontent.com/672121/108634092-d4a68d00-742c-11eb-8a1d-04feab8151a4.png">

Pro: easy to see all package info for a Fetch Job at a glance.

Con: takes up a lot of space. Makes Fetch Job row a lot longer.

**Comment by peterVG** [comment]
GUI option 2: display stats when hovering over an Info icon. next to total package count. Hide the stats when mouse moves away. 

![fetch-job-stats](https://user-images.githubusercontent.com/672121/108636701-df1c5300-743b-11eb-9913-1344e0f40e7b.gif)

Pro: conserves spaces. easy to see all package info for a Fetch Job in one glance.

**Comment by ross-spencer** [comment]
Love them both @peterVG. I like 2 most. How configurable is 2? Could it be a toggle, so click for the info and it displays. Click again and it disappears?

**Comment by peterVG** [comment]
Thanks @ross-spencer. I implemented a "hover" option in 'dev/package-stats-GUI' and submitted as PR. After fiddling with jQuery for a while I got stats display working when you hover the mouse over the Info icon. The stats are hidden again as soon as mouse moves away from the icon.

**Comment by ross-spencer** [comment]
@peterVG yep, it's looking good. Reason I ask about a toggle using a similar technique to the one you've adopted is that it might be nice to keep the information up on screen. Users might then toggle the information on between fetch jobs to compare without having to hover over and commit some of the info to memory. (I just generally like the idea of persisting information that is useful on screen but with the compromise here too that it doesn't by default use real-estate). What do you think? Is it at all feasible?

**Comment by peterVG** [comment]
Yeah, that's a good usability point. I'll try to implement that change and post and update here.

**Comment by peterVG** [comment]
I made the change from hover to click in the updated PR: https://github.com/artefactual-labs/AIPscan/pull/114

The behaviour now works as @ross-spencer suggested. Display on click for all info icons that are clicked. Hide the stats when the same info icon is clicked again.
