### ISSUE TITLE
Implement internationalization

### ISSUE THREAD

**Issue by peterVG** [artefactual-labs/AIPscan#50]

**Comment by mcantelon** [comment]
Flask-Babel looks pretty good for this:

https://phrase.com/blog/posts/python-localization-flask-applications/

**Comment by aseles13** [comment]
Closing this issue as this is not a priority at this time, can be re-opened at a later point.

**Comment by aseles13** [comment]
Closing this issue as this is not a priority at this time, can be re-opened at a later point.
