### ISSUE TITLE
Originals and Copies database tables could be collapsed into single Files table

### ISSUE THREAD

**Issue by tw4l** [artefactual-labs/AIPscan#55]
As can be seen in the ERD in https://github.com/artefactual-labs/AIPscan/issues/42, the AIPscan database currently has separate tables for original files (`originals`) and preservation derivatives (`copies`). The majority of fields for the two tables are identical, and it seems to me that they could be collapsed into a single `files` table.

This would make the development experience a bit smoother. As an example, to get information about the largest files, we currently have to query two tables:

```
if original_files is True:
    largest_files = originals.query.order_by(originals.size.desc()).limit(20)
else:
    largest_files = copies.query.order_by(copies.size.desc()).limit(20)
```

I'd prefer to be able to do something like:

```
largest_files = files.query.filter_by(type=file_type).order_by(files.size.desc()).limit(20)
```

Or, to get the largest files regardless of type, simply:

```
largest_files = files.query.order_by(files.size.desc()).limit(20)
```

We could manage the file type via a `type` field controlled by an enumerated list, or with a `is_original` boolean (the enumerated list might age better if we anticipate eventually tracking information about other types of files such as metadata and access derivatives in addition to original files and preservation derivatives).

**Comment by ross-spencer** [comment]
It's a plus one from me for simplicity. I do think this can be controlled by an enumerated list and that it might help in other reports too. You can see [here](https://github.com/artefactual-labs/AIPscan/blob/da8fc4c939a927cf0dbd54d7ab2fedc6f625e140/AIPscan/Data/data.py#L66-L69) I want to treat both types very similarly, but there is a small difference with there being a PUID or not. 

Do you see any problems creating a relationship to multiple derivatives though Tessa - in PR56 just logged, the dataverse original has two derivatives, for arguments sake, say a CSV and TAB. Does that make sense in a flatter structure, or should other parts of the files table sit independently from the rest? (one to many to a relationship lookup table?) (I can't quite see it in my head yet, but it's the end of the day, and a clue to head home for me!)

**Comment by tw4l** [comment]
I think multiple derivatives would still work well in a flatter table structure. As an overly simplified illustration (assuming a custom preservation rule that converts xslx to ods for preservation, just for demonstration), say we have a few types of derivatives for a single original file. The table could look something like:

| id | name | type | format | puid | derivative_of |
| --- | --- | --- | --- | --- | --- |
| 1 | my-research-data.xlsx | original | Microsoft Excel for Windows | fmt/214 | null |
| 2 | my-research-data.csv | derivative | Comma Separated Values | x-fmt/18 | 1 |
| 3 | my-research-data.tab | derivative | Plain Text File | x-fmt/111 | 1 |
| 4 | my-research-data.ods-UUID | preservation | OpenDocument Spreadsheet | null | 1 |
| 5 | another-original-file.pdf | original | Acrobat PDF 1.5 | fmt/19 | null |

It might be good if we both come back to it with fresh eyes but I think that would work fine in a flatter structure.

**Comment by peterVG** [comment]
Funny enough, I started with originals and preservation copies in the same table and then refactored them into separate tables at a later stage: https://github.com/artefactual-labs/AIPscan/commit/ab59e0667f008308b1884b85a601f3376ba14a2f#diff-1e7932912671e0180774b8fa39362873

TBH, I'm pretty sure I had a good reason at the time but honestly can't recall and unfortunately I looks like I didn't properly document the refactor commit, a downside of working in a one programmer silo without branch protection. Lesson learned.

It sounds like we now have a good reason to reverse this decision.  So I'm okay with that. It will probably require a bit of refactor in a number of places but hopefully Ross' data API introduction now minimizes that.

**Comment by tw4l** [comment]
Thanks for the context @peterVG! I think you're right that this will require a bit of a refactor, but I agree Ross' recent work should help with that. And of course better now than later on down the line! I'll take a stab at that soon - likely next week, given our current schedule with trainings.
