### ISSUE TITLE
Don't import duplicate AIPs

### ISSUE THREAD

**Issue by peterVG** [artefactual-labs/AIPscan#6]

**Comment by ross-spencer** [comment]
I wonder what the probability of a payload-oxum clashing is?
```
Bag-Software-Agent: bagit.py v1.7.0 <https://github.com/LibraryOfCongress/bagit-python>
Bagging-Date: 2020-07-07
External-Identifier: b354b687-cc3a-46cd-a2df-dc78027dab14
Payload-Oxum: 30195213.22
```
Also, we could use pointer files which I think might be a legitimate purpose for them here.

**Comment by peterVG** [comment]
So first of all, stating the obvious, we can't just check for already existing AIP UUIDs in the AIPscan dbase to see if we have a duplicate because an AIP could  have been re-ingested (but keep same UUID), right?

So is `Payload-Oxum` designed to detect changes in a Bagit package like a hash? If so, yes, that would be useful. However, I don't think this info is offered by `metsrw`. Is it even in the METS.xml? 

If not, we could consider creating and storing checksums for the METS.xml files. Presumably the METS file will change upon a re-ingest so its checksum will be different. However, this will likely be a heavy performance hit.

**Comment by tw4l** [comment]
Fix merged in https://github.com/artefactual-labs/AIPscan/pull/125, which requires deleting and recreating the database until we have migrations. Each METS file is hashed and the SHA-256 hash is subsequently stored in the database. On future fetch jobs the hash for downloaded METS is compared to the existing value and the METS is only processed (after deleting the records for the previous version of the AIP and its files) if the hash values don't match, indicating that the AIP METS has changed.
