### ISSUE TITLE
Model class names should be capitalized and singular

### ISSUE THREAD

**Issue by tw4l** [artefactual-labs/AIPscan#60]
AIPscan's model classes are currently all lowercase: https://github.com/artefactual-labs/AIPscan/blob/da8fc4c939a927cf0dbd54d7ab2fedc6f625e140/AIPscan/models.py

Per [PEP8](https://www.python.org/dev/peps/pep-0008/#class-names), class names should use the CapWords convention: 

Flask's own [style guide](https://flask.palletsprojects.com/en/1.1.x/styleguide/#naming-conventions) suggests the same, with the added suggestion that "acronyms kept uppercase (`HTTPWriter` and not `HttpWriter`)".

By convention, the class names should also be singular, so for example `storage_services` should be `StorageService`, `aips` should be `AIP` and so on.

This will make it easier to identify Models in the code base, e.g. when they are used in SQLAlchemy queries.

**Comment by tw4l** [comment]
Related to https://github.com/artefactual-labs/AIPscan/issues/55

**Comment by ross-spencer** [comment]
It makes it easier to find names for variables where, as an example, `agent` can happily be my instance of `Agent`.
