### ISSUE TITLE
Make Fetch Job activity display more meaningful

### ISSUE THREAD

**Issue by peterVG** [artefactual-labs/AIPscan#72]
In an earlier version of AiPscan the Fetch Job output console posted a notice of how many METS flles it was going to download and then numbered each METS file beingn downloaded so the user could get a sense of how far in the Fetch Job AIPscan is. This seems to have dissapeared in more recent commits:

<img width="425" alt="Screen Shot 2020-10-07 at 2 38 46 PM" src="https://user-images.githubusercontent.com/672121/95390944-05858b80-08ab-11eb-82f7-7fc246594cf4.png">

A similar numbering scheme was used to show progress in Parsing METS files but now multiple numbers are shown per Parsing job and are restarted for each new parsing job. This gives the user no sense of actual progress. 

The only thing the job console is useful for now is indicating that the server is actually busy and hasn't hung. Either we fix the display to re-introduce numbering or something similar or we should simplify the console to just have a "processing" indicator that is either green or red to indicate activity or a failure.

**Comment by ross-spencer** [comment]
Oh, interesting. Sorry about that Peter. This change wouldn't have been intentional, the use as you describe is superior. So we might need to look in more detail about what caused the regression and have a think about useful tests to avoid it again in future.
