### ISSUE TITLE
Add GUI element to largest files report to control number of files shown

### ISSUE THREAD

**Issue by tw4l** [artefactual-labs/AIPscan#77]
The largest files report (see #54) includes a "limit" parameter that can be used to specify how many results to include in the report. Currently this only works by adding `&limit=5` (for example) to the end of the report URL. It would be nice to include a GUI component to let users change the number of results shown without needing to manipulate the URL directly.

**Comment by tw4l** [comment]
Moving forward this could be a parameter passed from the report selection UI, rather than an element within the report page itself.

**Comment by mcantelon** [comment]
I've merged a PR to add these UI elements.
