### ISSUE TITLE
If the storage service url has trailing slash the fetch command will fail

### ISSUE THREAD

**Issue by peterVG** [artefactual-labs/AIPscan#8]
If the url for a configured storage service contains a trailing `/` character, then when we come to append the api command [here]( https://github.com/peterVG/AIPscan/blob/ce75f46cc2e7c5816cd2f15d29c1eac0be93dbc8/AIPscan/am_ss_requests.py#L10), we'll get a double `//` which causes the command to fail.

**Comment by ross-spencer** [comment]
Related https://github.com/artefactual-labs/AIPscan/issues/7 the ticket says it all, so as we fix this up and bring in AMClient we might find working with paths like this a lot easier.

**Comment by peterVG** [comment]
I can fix this with a simple form validation for now. Refactoring to use AMClient is a good suggestion but not trivial at this stage.

**Comment by ross-spencer** [comment]
Tiny fix for this and tests here https://github.com/artefactual-labs/AIPscan/pull/51/commits/c1eb64702797bb122962bbb6efbeefd1194ddb68 there might be a better long-term solution. This is useful to fix now as it helps with copy and paste.

**Comment by ross-spencer** [comment]
Continuing that fix here, it needed a little more effort: https://github.com/artefactual-labs/AIPscan/pull/51/commits/852e3d25ab3a78e27870e5b1c798a5f91953ffb8
