### ISSUE TITLE
Problem: Production deployments shouldn't be using Flask's development server

### ISSUE THREAD

**Issue by tw4l** [artefactual-labs/AIPscan#80]
Flask's development server [isn't intended for use in production and doesn't scale well](https://flask.palletsprojects.com/en/1.1.x/tutorial/deploy/#run-with-a-production-server).

One way to address this would be to create a WSGI entrypoint for gunicorn, and to run that behind nginx as a reverse proxy, similarly to how we deploy other Python applications. The [Deployment Options](https://flask.palletsprojects.com/en/1.1.x/deploying/) page in the Flask docs has details for a number of other options as well.

**Comment by ross-spencer** [comment]
@tw4l sorry to be that guy, but is is possible for you to describe this as `problem: statement of the problem`? This looks like a solution, but are there other alternatives we might consider here?

**Comment by tw4l** [comment]
@ross-spencer Yes, fair! The real problem is that we're using Flask's development server in production, which it isn't intended for, and I jumped to this solution based on what we use for other applications. But happy to take a step back - I'll modify the issue title now.

**Comment by tw4l** [comment]
Addressed in commit https://github.com/artefactual-labs/AIPscan/commit/c16a2a1452ffe987cd980304100d0f3b3c8b7fce, which includes instructions for how to serve AIPscan and its dependencies using gunicorn and persistent services.
