### ISSUE TITLE
Resolve circular imports to get AIPscan/__init__.py to pass linting

### ISSUE THREAD

**Issue by tw4l** [artefactual-labs/AIPscan#81]
Related to #35. See this comment particularly: https://github.com/artefactual-labs/AIPscan/issues/35#issuecomment-693650138

From cursory reading so far, this seems to be best resolved by following the [Application Factories](https://flask.palletsprojects.com/en/1.1.x/tutorial/factory/) Flask pattern. This should also help with #79.

**Comment by ross-spencer** [comment]
@tw4l as this is now a separate issue maybe we can also close out #35 some-how or get some commentary on that? Perhaps we can take the temporary approach I describe in the comment there and disable the warnings around the circular imports - that way we would have linting on and ready to go so we can immediately take advantage of that - and then this issue sits as a discrete new task. What do you think? @peterVG, thoughts too?

**Comment by tw4l** [comment]
@ross-spencer Agreed, I think the temporary approach you described would be a a good way forward so that we still get the benefits of #35, so I'm in favour.

**Comment by peterVG** [comment]
Also related to #31

**Comment by tw4l** [comment]
Resolved in https://github.com/artefactual-labs/AIPscan/pull/88
