### ISSUE TITLE
The total format size count doesn't have exception handling for None values

### ISSUE THREAD

**Issue by peterVG** [artefactual-labs/AIPscan#84]
![Screen Shot 2020-10-21 at 11 58 17 AM](https://user-images.githubusercontent.com/672121/96786729-86fa1500-13a5-11eb-8d76-c59d41760d41.png)

**Comment by ross-spencer** [comment]
You can `try/except` here, but you can also use `.get("size", 0)` to control the value. Do we know why this value isn't found? Is it the difference between originals/normalized values causing this?

**Comment by mcantelon** [comment]
The below fix works but agreed that there should be no null values in the DB so I'm going to close this as there's no way to replicate it. If whatever caused the null value wasn't fixed at some point we can create a new issue for it.

    -                size = original.size
    +                size = original.size if original.size is not None else 0
