### ISSUE TITLE
Start and end date parameters should be optional in reports UI and/or have different defaults

### ISSUE THREAD

**Issue by tw4l** [artefactual-labs/AIPscan#85]
The current UI for the `/reporter/reports/` page requires that a start date and end date are entered for any report that accepts them as parameters. The defaults set in the `AIPscan.Reporter.views.report` view and passed to the `reports.html` template are currently set to January 1 of the current year for start date, and today's date for the end date.

This means if I am a long-time Archivematica user and I want to generate a report that accepts date parameters (e.g. a "File format count" report) for all AIPs in my AIP store, I will need to go manually change the start date to the day I ingested my first AIP or before.

I think it would be better to set these defaults based on the actual earliest and latest AIP creation dates for a given Storage Service, which could be calculated as a `StorageService` model property, so that the default is always "all of my AIPs" and/or making the date parameters disabled by default and only activated when a user chooses to use them.

**Comment by ablwr** [comment]
Closed via https://github.com/artefactual-labs/AIPscan/pull/127
