### ISSUE TITLE
Filter reports by storage location

### ISSUE THREAD

**Issue by tw4l** [artefactual-labs/AIPscan#87]
At the October 22 sprint meeting, it was requested that reports should be filterable by storage location within a Storage Service. This might require extending the `StorageService` or `AIP` model to add the concept of storage location.

**Comment by peterVG** [comment]
This new feature is very comprehensive and looking really good @tw4l nice work!

After a successful Fetch Job run, my AIPs and files can be filtered according to Storage Location from the Report dashboards page As well, given my 3 test Storage Locations, the "All locations" option reports the correct aggregate number of AIPs.

I like how if a Storage Location filter is selected, then that shows as part of the report header metadata:

![image](https://user-images.githubusercontent.com/672121/120859530-32bd3300-c539-11eb-9417-00dea9136c5e.png)

But if “All locations” is selected then the “Location” element is simply left out:

![image](https://user-images.githubusercontent.com/672121/120859631-54b6b580-c539-11eb-9f08-f4f414335548.png)

When we create proper user docs we should make note that that to maximize this feature's effectiveness, the Archivematica Admin should override the confusing action tense of the current default AM SS Location description and use something more descriptive.

For example, from this:
![image](https://user-images.githubusercontent.com/672121/120850642-8ffeb780-c52c-11eb-86b5-b0e1c02bcd8f.png)

To this:
<img width="845" alt="Screen Shot 2021-06-04 at 2 23 58 PM" src="https://user-images.githubusercontent.com/672121/120864111-8c752b80-c540-11eb-9d7e-15deae9e1af7.png">

Note that I had to completely destroy my AIPscan database to generate this ^ screencap.

I first renamed the awkwardly titled "Store AIP in standard Archivematica Directory" to "Default AIP Store" in the Storage Service:

<img width="1349" alt="Screen Shot 2021-06-04 at 1 06 36 PM" src="https://user-images.githubusercontent.com/672121/120858237-5f704b00-c537-11eb-8e74-65bdfdd94e30.png">

Then I deleted the 2 Fetch Jobs in my AIPscan database. I had zero Fetch Jobs. Then I started a new Fetch Job, expecting to pull in the 2 new Storage Location descriptions and the updated default storage location description. But this is what I saw instead.
<img width="1154" alt="Screen Shot 2021-06-04 at 1 06 15 PM" src="https://user-images.githubusercontent.com/672121/120858514-bd049780-c537-11eb-8527-ed20ccb86bb9.png">

The default storage location still has the old name (description). So it looks like there is no cascade delete between the Fetch Job records and Storage Location records which makes sense considering it's a M:1 relationship. That said, if the relationship is down to 1:1 and a delete request comes though then maybe Cascade Delete should kick in to avoid this error. Is there a reason to keep a Storage Location record after it has zero associated Fetch Job records?

After I deleted the AIPscan project directory and database completely and pulled down a new `git clone`. I ran a new a Fetch Job against my SS which now had 3 Storage Locations: my renamed "Default AIP Store" and the two new "Alternative Storage ABC" and "Alternative Storage XYZ"

The file format report for the "Default AIP store" shows the correct number of AIPs:
<img width="1444" alt="Screen Shot 2021-06-04 at 2 43 33 PM" src="https://user-images.githubusercontent.com/672121/120865659-4ff6ff00-c543-11eb-98d9-8169071850cd.png">

However, the new AIP Storage Locations report only shows 2 AIPs and 8.2 MB of storage for the Default location, which is wrong.

<img width="1454" alt="Screen Shot 2021-06-04 at 2 36 50 PM" src="https://user-images.githubusercontent.com/672121/120865790-8b91c900-c543-11eb-81c4-5bb5a967bc97.png">

Are you seeing anything quirky like this on your side? What if you did a teardown and install like I did. Could I have left something behind somewhere that is now giving me bad data?

**Comment by tw4l** [comment]
Thanks @peterVG! A few in-line comments:

> When we create proper user docs we should make note that that to maximize this feature's effectiveness, the Archivematica Admin should override the confusing action tense of the current default AM SS Location description and use something more descriptive.

Totally agree. Note that we have an issue for the confusing default language here: https://github.com/archivematica/Issues/issues/1271

> The default storage location still has the old name (description).

Nice catch! I'll fix that.

> Is there a reason to keep a Storage Location record after it has zero associated Fetch Job records? Can/should we delete it?

Yes, good point! As you point out, the Storage Location and Fetch Job don't have a direct connection at the minute. It'd be many-to-many: one Fetch Job can pull information on many Storage Locations, and one Storage Location can be spread across many Fetch Jobs. I thought that it made sense to associate them at the Storage Service and AIP levels. I'll look into the deletion question.

> However, the new AIP Storage Locations report only shows 2 AIPs and 8.2 MB of storage for the Default location, which is wrong. Are you seeing anything quirky like this on your side?

I'll try to replicate, but is there a chance that the date filters on the AIP Storage Locations report is what's causing the discrepancy? The AIP Contents report doesn't filter on date yet so would ignore the set values for Start date and End date.

> What if you did a teardown and install like I did. Could I have left something behind somewhere that is now giving me bad data?

Deleting the database on each install will clear this, and would be recommended procedure until we have migrations.

**Comment by tw4l** [comment]
Okay, I have made two changes:

1. Storage Location descriptions are updated on subsequent Fetch Jobs if they change in the Storage Service.
2. Storage Locations are only displayed in the Reports and AIPs pages if they have associated AIPs. If a Fetch Job is deleted and that cascade deletes all of a Storage Location's AIPs, that Storage Location will no longer display in the UI. It is retained in the database and re-used if a future Fetch Job has AIPs from the same Storage Location.

**Comment by peterVG** [comment]
Classy. Thank you.

**Comment by peterVG** [comment]
The quirky storage location stats turned out to be a browser cache issue. It works correctly:
<img width="1329" alt="Screen Shot 2021-06-09 at 7 36 27 AM" src="https://user-images.githubusercontent.com/672121/121407874-9ddd7f80-c914-11eb-91d7-142021693f46.png">

**Comment by peterVG** [comment]
Updating renamed Storage Locations is working. This is after a second rename and second fetch job:

<img width="686" alt="Screen Shot 2021-06-09 at 11 30 37 AM" src="https://user-images.githubusercontent.com/672121/121409309-345e7080-c916-11eb-8969-d38eaaaf48a8.png">

**Comment by peterVG** [comment]
Testing for storage location delete/display toggle:

1. create brand new AM storage service location
2. store an AIP on it
3. run a new Fetch job from AIPscan which already has data from other storage locations

<img width="1283" alt="Screen Shot 2021-06-09 at 11 47 34 AM" src="https://user-images.githubusercontent.com/672121/121411800-ded79300-c918-11eb-8cc1-6608e315a3f2.png">

4. confirm the new Fetch Job and Storage Location in AIPscan

<img width="668" alt="Screen Shot 2021-06-09 at 11 51 49 AM" src="https://user-images.githubusercontent.com/672121/121412034-1b0af380-c919-11eb-8671-899263aa0acd.png">

5. delete the Fetch Job. 
6. SInce there are no more AIPs in the database that are stored in that Location, confirm that this Storage Location no longer appears as an option in GUI drop-downs

<img width="615" alt="Screen Shot 2021-06-09 at 11 49 10 AM" src="https://user-images.githubusercontent.com/672121/121412196-48f03800-c919-11eb-9057-42c3b916c0a8.png">

Works!

**Comment by peterVG** [comment]
Related PR approved https://github.com/artefactual-labs/AIPscan/pull/134
