### ISSUE TITLE
Delete storage service doesn't remove agents

### ISSUE THREAD

**Issue by ross-spencer** [artefactual-labs/AIPscan#91]
This looks to be an oversight of the agents work. If you have agents in your database they won't be removed with the delete storage service job. It will become more apparent in testing as you test with two or three user agents with different names. 

To recreate, simply delete a storage service from AIPscan and then check out `aipscan.db` in `sqlite3`.

**Comment by mcantelon** [comment]
Possible implementation:

1. Add a storage service ID field to the Agent model (defined in `AIPscan/models.py`):
```
    storage_service_id = db.Column(
        db.Integer(), db.ForeignKey("storage_service.id"), nullable=False
    )
```
2. Add a storage service ID argument to the `create_agent_objects` function (in `AIPscan/Aggregator/database_helpers.py`)
3. Change the call to `create_agent_objects` in the `process_aip_data` function (in the same file) to include the storage service ID from the AIP object argument (`aip.storage_service_id`)
4. Make sure `delete_storage_service` (in `AIPscan/Aggregator/views.py`) deletes the agents for the storage service when run

**Comment by melaniekung** [comment]
Fix for this has now been merged.
